import {
  iconHtmlColor,
  iconHtmlWhite,
  iconCssColor,
  iconCssWhite,
  iconJsWhite,
  iconJsColor,
  iconReactColor,
  iconReactWhite,
  iconGitColor,
  iconGitWhite,
  iconGithub,
  iconNpmColor,
  iconNpmWhite,
  iconReduxColor,
  iconReduxWhite,
  iconTailwindColor,
  iconTailwindWhite,
  iconWebpackColor,
  iconWebpackWhite,
  iconTsColor,
  iconTsWhite,
  iconVsCodeWhite,
  iconVsCodeColor,
} from "../../Icons";

const techTextEn = {
  technologies: [
    {
      title: "HTML5",
      color: "#E34F26",
      iconWhite: iconHtmlWhite,
      iconColor: iconHtmlColor,
      level: "Advanced",
      mainTopics: [
        "Semantic structure",
        "HTML tags",
        "Forms",
        "Multimedia (audio, video)",
      ],
      mainProjects: ["personal portfolio", "e-commerce site"],
    },
    {
      title: "CSS3",
      color: "#1572B6",
      iconWhite: iconCssWhite,
      iconColor: iconCssColor,
      level: "Advanced",
      mainTopics: [
        "Selectors and combinators",
        "Flexbox and Grid",
        "Libraries (Tailwind, Bootstrap)",
        "Animations and transitions",
        "CSS methodologies (BEM, SMACSS)",
        "Responsive Design",
      ],
      mainProjects: ["personal portfolio", "e-commerce site"],
    },
    {
      title: "JavaScript",
      color: "#F7DF1E",
      iconWhite: iconJsWhite,
      iconColor: iconJsColor,
      level: "Intermediate",
      mainTopics: [
        "Arrow functions",
        "Destructuring",
        "Promises and Async/Await",
        "DOM manipulation",
        "ES6 modules",
      ],
      mainProjects: ["technology blog", "task management app"],
    },
    {
      title: "TypeScript",
      color: "#3178C6",
      iconWhite: iconTsWhite,
      iconColor: iconTsColor,
      level: "Basic",
      mainTopics: ["Static types", "Interfaces", "Generics", "Decorators"],
      mainProjects: ["task management app"],
    },
  ],
  frameworksLibraries: [
    {
      title: "React.js",
      color: "#61DAFB",
      iconWhite: iconReactWhite,
      iconColor: iconReactColor,
      level: "Intermediate",
      mainTopics: [
        "Components",
        "Hooks",
        "State Management",
        "React Router",
        "JSX",
      ],
      mainProjects: ["personal portfolio", "technology blog"],
    },
    {
      title: "Redux",
      color: "#764ABC",
      iconWhite: iconReduxWhite,
      iconColor: iconReduxColor,
      level: "Intermediate",
      mainTopics: [
        "State Management",
        "Actions",
        "Reducers",
        "Middleware",
        "Redux Toolkit",
      ],
      mainProjects: [
        "State management in an e-commerce app",
        "Task management app with global state management",
      ],
    },
    {
      title: "Tailwind CSS",
      color: "#38B2AC",
      iconWhite: iconTailwindWhite,
      iconColor: iconTailwindColor,
      level: "Intermediate",
      mainTopics: ["CSS utilities", "Theme customization", "Responsive Design"],
      mainProjects: ["personal portfolio"],
    },
  ],
  tools: [
    {
      title: "Git",
      color: "#F05032",
      iconWhite: iconGitWhite,
      iconColor: iconGitColor,
      level: "Intermediate",
      mainTopics: [
        "Basic commands (add, commit, push)",
        "Branches",
        "Merge",
        "Rebase",
      ],
      mainProjects: ["personal portfolio", "technology blog"],
    },
    {
      title: "GitHub",
      color: "#181717",
      iconWhite: iconGithub,
      iconColor: iconGithub,
      level: "Intermediate",
      mainTopics: ["Pull requests", "Project collaboration", "GitHub Actions"],
      mainProjects: ["personal portfolio", "e-commerce site"],
    },
    {
      title: "npm/Yarn",
      color: "#CB3837",
      iconWhite: iconNpmWhite,
      iconColor: iconNpmColor,
      level: "Intermediate",
      mainTopics: ["Dependency management", "Scripts", "Project configuration"],
      mainProjects: ["technology blog", "task management app"],
    },
    {
      title: "Webpack",
      color: "#8DD6F9",
      iconWhite: iconWebpackWhite,
      iconColor: iconWebpackColor,
      level: "Basic",
      mainTopics: ["Basic configuration", "Loaders", "Plugins"],
      mainProjects: [],
    },
    {
      title: "VS Code",
      color: "#007ACC",
      iconWhite: iconVsCodeWhite,
      iconColor: iconVsCodeColor,
      level: "Advanced",
      mainTopics: [
        "Useful extensions",
        "Keyboard shortcuts",
        "Custom configurations",
      ],
      mainProjects: ["personal portfolio", "task management app"],
    },
  ],
  conceptsMethodologies: [
    {
      title: "Responsive Design",
      color: "#34A853",
      level: "Intermediate",
      mainTopics: ["Media queries", "Mobile-first design", "Flexbox and Grid"],
      mainProjects: ["personal portfolio", "e-commerce site"],
    },
    {
      title: "Reusable Components",
      color: "#007BFF",
      level: "Intermediate",
      mainTopics: [
        "Component design",
        "Props and state",
        "Component composition",
      ],
      mainProjects: ["personal portfolio", "technology blog"],
    },
    {
      title: "State Management",
      color: "#6A1B9A",
      level: "Intermediate",
      mainTopics: ["React useState/useReducer", "Redux", "Vuex"],
      mainProjects: ["task management app", "technology blog"],
    },
    {
      title: "AJAX and Fetch API",
      color: "#FF5722",
      level: "Intermediate",
      mainTopics: ["HTTP requests", "Promises", "Error handling"],
      mainProjects: ["technology blog", "e-commerce site"],
    },
    {
      title: "RESTful APIs",
      color: "#FFC107",
      level: "Intermediate",
      mainTopics: [
        "REST principles",
        "CRUD",
        "Authentication and authorization",
      ],
      mainProjects: ["task management app", "e-commerce site"],
    },
    {
      title: "Cross-Browser Compatibility",
      color: "#607D8B",
      level: "Basic",
      mainTopics: [
        "Testing across different browsers",
        "Polyfills",
        "Development tools",
      ],
      mainProjects: [],
    },
    {
      title: "Basic SEO",
      color: "#2196F3",
      level: "Basic",
      mainTopics: ["Content optimization", "Meta tags", "Performance"],
      mainProjects: ["personal portfolio", "technology blog"],
    },
    {
      title: "Web Accessibility (a11y)",
      color: "#9C27B0",
      level: "Basic",
      mainTopics: ["Keyboard accessibility", "ARIA labels", "Color contrast"],
      mainProjects: [],
    },
    {
      title: "Testing",
      color: "#FFEB3B",
      level: "Basic",
      mainTopics: ["Unit tests", "Jest", "React Testing Library"],
      mainProjects: [],
    },
    {
      title: "Agile/Scrum",
      color: "#795548",
      level: "Basic",
      mainTopics: ["Sprint Planning", "Daily Standups", "Sprint Review"],
      mainProjects: [],
    },
    {
      title: "Version Control with Git",
      color: "#F44336",
      level: "Intermediate",
      mainTopics: ["Branches", "Pull requests", "Merge conflicts"],
      mainProjects: ["personal portfolio", "task management app"],
    },
    {
      title: "Continuous Integration/Continuous Deployment (CI/CD)",
      color: "#00BCD4",
      level: "Basic",
      mainTopics: ["Pipelines", "Automated testing", "Deployment"],
      mainProjects: [],
    },
  ],
};

export default techTextEn;
